# Generated by Django 3.0.5 on 2020-09-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Simple user'), ('moderator', 'Website moderator'), ('admin', 'Administrator')], default='user', max_length=100),
        ),
    ]
