version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: sudomoinpavel/yamdb_final:latest
    restart: always
    command: bash -c "python manage.py migrate --noinput && python manage.py collectstatic && python manage.py loaddata fixtures.json && --noinput && gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8020"
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "8020:8020"
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      -  web