name: yamdb_final_workflow

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    #needs: build_and_push_to_docker_hub
    steps:
      - uses: actions/checkout@master
      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: 'docker-compose.yaml, nginx.conf'
          target: '/home/praktikum-python/yamdb_final/'
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd yamdb_final
            sudo docker pull sudomoinpavel/yamdb_final:latest
            sudo docker-compose up --force-recreate -d

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} успешно выполнен!
